<?php

/**
 * تنظيف خريطة أصناف Composer من الإدخالات التي تشير إلى ملفات غير موجودة.
 *
 * لماذا: الخريطة تُولَّد وقت التثبيت. نقل ملف أو حذفه يترك إدخالًا يشير إلى
 * مسار غير موجود، فيفشل include عند أول تحميل — والأصناف المُحمَّلة عبر حاوية
 * Laravel وقت الطلب هي التي تسقط دون غيرها، فيبدو الموقع سليمًا حتى يزور
 * أحدهم صفحة متأثرة.
 *
 * لماذا لا composer dump-autoload وحده: قد لا يكون Composer مثبَّتًا على
 * الاستضافة المشتركة. هذا بديل لا يحتاج إلا PHP.
 *
 * لماذا الحذف كافٍ وآمن: أصناف App\ تُحلّ بـPSR-4 حين تغيب من الخريطة، فحذف
 * إدخال قديم يعيدها إلى مسارها الصحيح. الحذف لا يضيف سلوكًا بل يزيل اختصارًا
 * صار كاذبًا.
 *
 * **الملف الحاسم هو autoload_static.php لا autoload_classmap.php.** عند التوليد
 * المُحسَّن (-o) يقرأ autoload_real.php الأول وحده دون شرط، ولا يلمس الثاني
 * إطلاقًا. أول نسخة من هذا السكربت عالجت الثاني فقط، فكانت بلا أثر رغم أنها
 * تبدو صحيحة.
 *
 * الاستخدام: php deploy/prune-classmap.php [--dry-run]
 * رمز الخروج: 0 نجاح · 1 خطأ.
 */
$root = dirname(__DIR__);
$vendorComposer = $root.'/vendor/composer';
$dryRun = in_array('--dry-run', $argv, true);

if (! is_dir($vendorComposer)) {
    fwrite(STDERR, "لا يوجد vendor/composer — شغّل composer install أولًا.\n");
    exit(1);
}

$totalPruned = 0;

/**
 * يفكّ تعبير المسار المولَّد: __DIR__ . '/../..' . '/app/X.php'
 * أو سلسلة حرفية. يعيد null إن تعذّر الفهم — فلا يُحذف السطر عندها.
 */
$resolve = static function (string $expression) use ($vendorComposer): ?string {
    $expression = trim(rtrim($expression, ','));
    $usesDir = str_starts_with($expression, '__DIR__');

    if (! preg_match_all("/'((?:[^'\\\\]|\\\\.)*)'/", $expression, $matches)) {
        return null;
    }

    $path = '';
    foreach ($matches[1] as $segment) {
        $path .= stripcslashes($segment);
    }

    if ($path === '') {
        return null;
    }

    return $usesDir ? $vendorComposer.$path : $path;
};

// ---------------------------------------------------------------------------
// autoload_static.php — ما يقرأه التشغيل فعلًا.
// ---------------------------------------------------------------------------
$staticFile = $vendorComposer.'/autoload_static.php';

if (is_file($staticFile)) {
    $lines = file($staticFile);
    $inMap = false;
    $kept = [];
    $pruned = 0;

    foreach ($lines as $line) {
        if (! $inMap) {
            $kept[] = $line;
            if (str_contains($line, 'public static $classMap = array (')) {
                $inMap = true;
            }

            continue;
        }

        if (preg_match('/^\s*\);\s*$/', $line)) {
            $inMap = false;
            $kept[] = $line;

            continue;
        }

        $arrow = strpos($line, '=>');
        $path = $arrow === false ? null : $resolve(substr($line, $arrow + 2));

        if ($path !== null && ! is_file($path)) {
            $pruned++;

            continue;
        }

        $kept[] = $line;
    }

    if ($pruned === 0) {
        echo "autoload_static.php: سليم.\n";
    } elseif ($dryRun) {
        echo "autoload_static.php: {$pruned} إدخالًا قديمًا (تجربة جافة).\n";
    } else {
        copy($staticFile, $staticFile.'.bak');
        file_put_contents($staticFile, implode('', $kept));

        // التحقق في عملية منفصلة: تضمين الملف هنا يعلن الصنف مرتين.
        exec(escapeshellarg(PHP_BINARY).' -l '.escapeshellarg($staticFile).' 2>&1', $out, $code);

        if ($code !== 0) {
            copy($staticFile.'.bak', $staticFile);
            fwrite(STDERR, "الناتج غير صالح — استُرجعت النسخة الأصلية.\n");
            exit(1);
        }

        echo "autoload_static.php: حُذف {$pruned} إدخالًا.\n";
        $totalPruned += $pruned;
    }
}

// ---------------------------------------------------------------------------
// autoload_classmap.php — يقرأه التوليد غير المُحسَّن. يُنظَّف للاتساق.
// ---------------------------------------------------------------------------
$mapFile = $vendorComposer.'/autoload_classmap.php';

if (is_file($mapFile)) {
    $map = require $mapFile;

    if (is_array($map)) {
        $stale = array_filter(
            $map,
            static fn ($path) => ! is_string($path) || ! is_file($path),
        );

        if ($stale === []) {
            echo "autoload_classmap.php: سليم.\n";
        } elseif ($dryRun) {
            echo 'autoload_classmap.php: '.count($stale)." إدخالًا قديمًا (تجربة جافة).\n";
        } else {
            copy($mapFile, $mapFile.'.bak');

            $body = "<?php\n\n// autoload_classmap.php @generated by Composer\n"
                ."// نُظِّف بـdeploy/prune-classmap.php\n\n"
                ."\$vendorDir = dirname(__DIR__);\n\$baseDir = dirname(\$vendorDir);\n\nreturn array(\n";

            foreach (array_diff_key($map, $stale) as $class => $path) {
                $body .= '    '.var_export($class, true).' => '.var_export($path, true).",\n";
            }

            file_put_contents($mapFile, $body.");\n");
            echo 'autoload_classmap.php: حُذف '.count($stale)." إدخالًا.\n";
            $totalPruned += count($stale);
        }
    }
}

if ($totalPruned > 0) {
    echo "تمّ. الأصناف المحذوفة ستُحلّ بـPSR-4.\n";
}

exit(0);
