<?php

return [
    'blueprint' => ['key' => 'smart-marketing-consultation', 'name' => 'الاستشارة التسويقية الذكية', 'version' => 2],
    'depth_limits' => ['quick' => 18, 'standard' => 35, 'deep' => 60],
    'source_confidence' => ['system' => 'high', 'file' => 'high', 'extracted' => 'medium', 'user' => 'medium', 'estimate' => 'low', 'inference' => 'low'],
    'modules' => [
        ['key' => 'scope', 'name' => 'النطاق والمرحلة والأهداف', 'tool' => 'marketing-score', 'required' => true],
        ['key' => 'business-model', 'name' => 'نموذج العمل والعرض', 'tool' => 'offer-builder', 'required' => true],
        ['key' => 'customer-b2c', 'name' => 'العميل الفرد', 'tool' => 'audience-map'],
        ['key' => 'customer-b2b', 'name' => 'العميل المؤسسي', 'tool' => 'audience-map'],
        ['key' => 'market-competition', 'name' => 'السوق والمنافسة', 'tool' => 'competitor-lens', 'required' => true],
        ['key' => 'positioning-brand', 'name' => 'القيمة والتموضع والعلامة', 'tool' => 'brand-clarity', 'required' => true],
        ['key' => 'pricing-economics', 'name' => 'التسعير والاقتصاديات', 'tool' => 'offer-builder'],
        ['key' => 'marketing-channels', 'name' => 'التسويق والقنوات', 'tool' => 'channel-fit'],
        ['key' => 'content', 'name' => 'المحتوى', 'tool' => 'content-engine'],
        ['key' => 'paid-ads', 'name' => 'الإعلانات المدفوعة', 'tool' => 'campaign-planner'],
        ['key' => 'conversion', 'name' => 'الموقع والتطبيق والتحويل', 'tool' => 'funnel-audit'],
        ['key' => 'seo-geo', 'name' => 'SEO وGEO', 'tool' => 'seo-compass'],
        ['key' => 'sales', 'name' => 'المبيعات', 'tool' => 'funnel-audit'],
        ['key' => 'retention', 'name' => 'الاحتفاظ ودورة الحياة', 'tool' => 'marketing-score'],
        ['key' => 'crm-data', 'name' => 'CRM وMarTech والقياس', 'tool' => 'marketing-score'],
        ['key' => 'team-governance', 'name' => 'الفريق والحوكمة', 'tool' => 'agency-brief'],
        ['key' => 'go-to-market', 'name' => 'الدخول إلى السوق', 'tool' => 'campaign-planner'],
        ['key' => 'risk-security', 'name' => 'المخاطر والأمن الدفاعي', 'tool' => null],
        ['key' => 'priorities-execution', 'name' => 'الأولويات والتنفيذ', 'tool' => 'agency-brief', 'required' => true],
    ],
    'gateway_questions' => [
        ['key' => 'START-01', 'variable' => 'assessment_scope', 'text' => 'ما الذي تريد تقييمه؟ يمكنك اختيار أكثر من نطاق.', 'type' => 'multiselect', 'options' => ['فكرة جديدة', 'مشروع قائم', 'منتج أو خدمة', 'سوق جديد', 'حملة', 'موقع أو تطبيق', 'كل النشاط']],
        ['key' => 'START-02', 'variable' => 'offer_type', 'text' => 'ما طبيعة ما تقدمه؟ اختر كل ما ينطبق.', 'type' => 'multiselect', 'options' => ['منتج ملموس', 'منتج رقمي', 'خدمة', 'اشتراك', 'منصة', 'محتوى', 'غير ذلك']],
        ['key' => 'START-03', 'variable' => 'customer_type', 'text' => 'لمن تبيع غالبًا؟', 'options' => ['أفراد', 'شركات', 'جهات حكومية', 'أفراد وشركات', 'لا أعرف بعد']],
        ['key' => 'START-04', 'variable' => 'actual_stage', 'text' => 'إلى أي مرحلة وصل المشروع فعليًا؟', 'options' => ['فكرة', 'قبل الإطلاق', 'أول عملاء', 'مبيعات غير مستقرة', 'نمو', 'توسع', 'تراجع']],
        ['key' => 'START-05', 'variable' => 'primary_problem', 'text' => 'ما المشكلات التي تريد حلها؟ اختر كل ما ينطبق وسنرتب الأولوية لاحقًا.', 'type' => 'multiselect', 'options' => ['لا أعرف أين أبدأ', 'ضعف المبيعات', 'قلة العملاء', 'ارتفاع التكلفة', 'ضعف التحويل', 'تراجع العملاء', 'ضعف المحتوى', 'إطلاق جديد', 'مشكلة أخرى']],
        ['key' => 'START-06', 'variable' => 'primary_goal', 'text' => 'ما النتيجة الأهم خلال الفترة القادمة؟', 'options' => ['أول عملاء', 'زيادة المبيعات', 'زيادة الربح', 'خفض التكلفة', 'بناء الوعي', 'دخول سوق', 'تحسين الاحتفاظ', 'تنظيم الفريق', 'قياس الأداء']],
        ['key' => 'START-07', 'variable' => 'target_horizon', 'text' => 'خلال أي مدة تريد رؤية تقدم واضح؟', 'options' => ['أسبوعان', 'شهر', '3 أشهر', '6 أشهر', 'سنة', 'لم أحدد']],
        ['key' => 'START-08', 'variable' => 'data_level', 'text' => 'هل لديك بيانات أو تقارير يمكن الاعتماد عليها؟', 'options' => ['نعم وسأرفعها', 'أرقام متفرقة', 'تقديرات فقط', 'لا توجد بيانات']],
        ['key' => 'START-09', 'variable' => 'consultation_depth', 'text' => 'ما مستوى العمق الذي يناسب قرارك؟', 'options' => ['سريع', 'قياسي', 'متعمق', 'اقترح الأنسب']],
        ['key' => 'START-10', 'variable' => 'executor', 'text' => 'من سيشارك في تنفيذ التوصيات؟ اختر كل المشاركين.', 'type' => 'multiselect', 'options' => ['أنا', 'فريق داخلي', 'وكالة أو مستقلون', 'عدة جهات', 'لا أعرف']],
        ['key' => 'START-11', 'variable' => 'constraints', 'text' => 'ما القيود التي يجب مراعاتها؟', 'type' => 'multiselect', 'options' => ['ميزانية محدودة', 'وقت محدود', 'فريق صغير', 'قيود قانونية', 'قيود تقنية', 'لا توجد', 'أخرى']],
        ['key' => 'START-12', 'variable' => 'source_consent', 'text' => 'هل تسمح بتحليل الملفات والروابط التي تقدمها لتقليل الأسئلة؟', 'options' => ['نعم', 'نعم بعد المراجعة', 'لا']],
    ],
];
